### PR TITLE
fix: yubikey prompts for AWS and kubectl

### LINKED ISSUE #160: bug: Using credential_process with a yubikey does not prompt with Touch your YubiKey...
I have set up aws-vault with my yubikey and it's working fine, but when I issue an `aws` command and there is no session cached, I don't get prompted to touch my yubikey.

When I call `aws-vault` directly, I get prompted, as expected, eg:
```
$ aws-vault export --format=json --prompt=ykman er0k
Touch your YubiKey...
^C
```

but when calling `aws` directly, there is no prompt. It just hangs there, and eventually times out:
```
$ aws sts get-caller-identity

Error when retrieving credentials from custom-process: Touch your YubiKey...
ERROR: Touch account timed out!
aws-vault: error: exec: Failed to get credentials for er0k: process provider: exit status 1
```

If I touch the yubikey before the timeout it does work, but it can be hard to tell if it's waiting for input from me or AWS is just being slow 😛 

My aws config looks like this:
```
[profile er0k]
mfa_serial=arn:aws:iam::1234567890:mfa/yubivirt
mfa_process = ykman oath accounts code --single arn:aws:iam::1234567890:mfa/yubivirt
credential_process = aws-vault export --format=json --prompt=ykman er0k
```

I have also tried using the `terminal` prompt driver instead of `ykman`, but the behavior is the same. 

I've also noticed `kubectl` (using EKS) does _not_ show the prompt. But `docker` (using ECR) and `terraform` (using S3 for state storage) both prompt with `Touch your YubiKey...` correctly.

Is there any way to get `aws` and `kubectl` commands  to prompt with `Touch your YubiKey...` ?

- [x] I am using the latest release of AWS Vault
- [x] I have provided my `.aws/config` (redacted if necessary)
- [ ] I have provided the debug output using `aws-vault --debug` (redacted if necessary)

### PR DESCRIPTION
**Pull request by er0k**
Fixes #160.

I used Claude Code to fix this bug. Tested on macOS 15.6.1 and Debian forky/sid. I don't have a Windows machine available to test there, hopefully someone else can verify that works.

Here is Claude's summary of the fix:

When aws-vault is used as a credential_process subprocess, the parent process (aws CLI, kubectl, docker, terraform) pipes stdout to capture the JSON credentials output. Some tools also capture stderr. Docker's credential helper protocol additionally pipes JSON to aws-vault's stdin, which propagates down when aws-vault spawns its mfa_process command.

Root cause: executeMFACommand (vault/mfa_unix.go) and YkmanMfaProvider (prompt/ykman.go) both inherited aws-vault's file descriptors without modification. With stderr captured by the parent, the "Touch your YubiKey..." prompt was invisible. With stdin piped from docker, ykman's sys.stdin.isatty() returned False, causing its click_prompt helper to attempt a readline() from the pipe (returning EOF), then fall through to click.prompt() which failed with exit code 1.

Fix: open /dev/tty with O_RDWR and assign it as both cmd.Stdin and cmd.Stderr for the subprocess. This ensures:

- The touch prompt is always visible on the real terminal regardless of how the parent process wired up aws-vault's stderr.
- The subprocess always sees a real TTY as stdin, so ykman's sys.stdin.isatty() returns True and interactive prompts (e.g. OATH password entry) work correctly in all calling contexts.
- No terminal mode (termios) manipulation occurs, so the fix does not disrupt callers that already work (terraform, bare shell).
- Falls back to os.Stderr if /dev/tty is unavailable.

The Windows equivalent (vault/mfa_windows.go) opens CONIN$ for stdin and CONOUT$ for stderr separately, as Windows does not have a single read-write console device node.

Files changed:
- vault/mfa_unix.go: O_WRONLY -> O_RDWR, add cmd.Stdin = ttyFile
- vault/mfa_windows.go: add CONIN$ open for cmd.Stdin
- prompt/ykman.go: same O_RDWR + cmd.Stdin change as mfa_unix.go

Tests added (vault/mfa_unix_test.go):
- CapturesStdout: stdout from mfa_process is returned as the token
- TrimsWhitespace: surrounding whitespace/newlines are stripped
- StderrNotCaptured: stderr does not bleed into the captured token
- CommandFailure: non-zero exit code is returned as an error
- StdinIsTTY: subprocess stdin is a TTY when /dev/tty is available; skipped automatically in headless CI environments

### CODE REVIEW

File: prompt/ykman.go [hunk 1]
```diff
@@ -35,7 +35,21 @@ func YkmanMfaProvider(mfaSerial string) (string, error) {
...
+	//   - Stderr: the "Touch your YubiKey..." prompt is visible even when
+	//     aws-vault is spawned as a credential_process subprocess (where the
+	//     parent process may capture os.Stderr via a pipe).
+	//   - Stdin: ykman gets a real TTY as stdin so sys.stdin.isatty() == True,
+	//     allowing interactive prompts (e.g. OATH password) to work even when
+	//     aws-vault's stdin is a pipe (e.g. docker credential helper).
+	if ttyFile, err := os.OpenFile("/dev/tty", os.O_RDWR, 0); err == nil {
+		cmd.Stdin = ttyFile
+		cmd.Stderr = ttyFile
+		defer ttyFile.Close()
```
Comment (mbevc1) [inline prompt/ykman.go]: Minor nit: I'd put this outside `if`

File: vault/mfa_unix.go [hunk 2]
```diff
@@ -12,7 +12,22 @@ import (
...
+	//     visible even when aws-vault's stderr is captured by the parent
+	//     process (e.g. aws CLI or kubectl using credential_process).
+	//   - Stdin: subprocess gets a real TTY as stdin so that tools like ykman
+	//     see sys.stdin.isatty() == True and can display interactive prompts
+	//     (e.g. OATH password) even when aws-vault's stdin is a pipe
+	//     (e.g. docker credential helper receiving JSON on stdin).
+	if ttyFile, err := os.OpenFile("/dev/tty", os.O_RDWR, 0); err == nil {
+		cmd.Stdin = ttyFile
+		cmd.Stderr = ttyFile
+		defer ttyFile.Close()
```
Comment (mbevc1) [inline vault/mfa_unix.go]: Minor nit: I'd put this outside `if`

File: vault/mfa_windows.go [hunk 3]
```diff
@@ -17,7 +17,22 @@ func executeMFACommand(processCmd string) (string, error) {
 	shell := os.Getenv("SystemRoot") + "\\System32\\cmd.exe"
 	cmd := exec.Command(shell)
 	cmd.SysProcAttr = &syscall.SysProcAttr{CmdLine: "/C \"" + processCmd + "\""}
-	cmd.Stderr = os.Stderr
+	// Connect stdin to the console so that interactive prompts (e.g. OATH
+	// password) work even when aws-vault's stdin is a pipe (e.g. docker
+	// credential helper receiving JSON on stdin).
+	if inFile, err := os.OpenFile("CONIN$", os.O_RDONLY, 0); err == nil {
+		cmd.Stdin = inFile
+		defer inFile.Close()
```
Comment (mbevc1) [inline vault/mfa_windows.go]: Minor nit: I'd put this outside `if`

File: vault/mfa_windows.go [hunk 4]
```diff
@@ -17,7 +17,22 @@ func executeMFACommand(processCmd string) (string, error) {
...
+	}
+	// Connect stderr to the console so interactive prompts (e.g. "Touch your
+	// YubiKey...") are visible even when aws-vault's stderr is captured by the
+	// parent process.
+	if outFile, err := os.OpenFile("CONOUT$", os.O_WRONLY, 0); err == nil {
+		cmd.Stderr = outFile
+		defer outFile.Close()
```
Comment (mbevc1) [inline vault/mfa_windows.go]: Minor nit: I'd put this outside `if`

**Comment by mbevc1** [comment]
Thanks @er0k :rocket: looks good !

I left few minor nits for `defer` and checks will pass if you could change to conventional commits.

Not a blocker, but Windows is untested, if you add those that should get tested by CI.

**Comment by er0k** [comment]
thanks @mbevc1, I amended my commit to use conventional commits, used the suggested defer-outside-if pattern, and added some tests for mfa_windows :+1:

**Review by mbevc1 — APPROVED** [review]
